### ISSUE TITLE
feat(calling): call improvements 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/UplinkWeb#744]
# Task and Bug Tracker

## Tasks
- [x] Need to improve feedback when people leave the call (FEAT) - **Assigned to:** @Flemmli97 #762
- [x] Add feedback for users that are not in the call - **Assigned to:** @Flemmli97  #780
- [x] Show username underneath user who is not using video feed - [PR Opened](https://github.com/Satellite-im/UplinkWeb/pull/745) - **Assigned to:** @lgmarchi 
- [x] Reorder users in call prioritizing users with camera enabled - [PR Opened](https://github.com/Satellite-im/UplinkWeb/pull/747) - **Assigned to:** @lgmarchi 

## Bugs
- [ ] The pictures froze when everybody disables the camera (BUG) - **Assigned to:** NO ONE
- [x] UI for cameras enabled and some cameras not enabled is weird (BUG) - **Assigned to:** @Flemmli97 #759
- [x] It is missing talking indicator when camera is enabled (FEAT) - **Assigned to:** @Flemmli97 #761
- [ ] When trying to rejoin a group call sometimes a bug happens where once it shows users connected it hangups the call - **Assigned to:** NO ONE
- [x] Sometimes when in the middle of a call, you will get a ringtone and incoming call modal even though there is no call to answer - **Assigned to:** @lgmarchi 
- [ ] Sometimes only the group creator will be able to see who is still joining the call - **Assigned to:** NO ONE
- [x] Talking indicator doesn't appear whether user has video on or not - **Assigned to:** @Flemmli97 #769
- [x] User that is not a friend cannot see each other in the call (BUG) - PR Opened - **Assigned to:** @lgmarchi 
- [x] User that are not friends, can not listen each other (BUG) - PR Opened - **Assigned to:** @lgmarchi 
- [ ] Feedback for no response, and when people joined the call maybe is not correct when we have a lot of people in the call (BUG) **Assigned to:** @Flemmli97
